### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by mjarsulic** [NCI-GDC/gdc-client#102]
Have installed the gcc-client v1.0.1 and am getting the following syntax error:

# gdc-client 
Traceback (most recent call last):
  File "/usr/bin/gdc-client", line 5, in <module>
    pkg_resources.run_script('gdc-client==v1.0.1', 'gdc-client')
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 745, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1670, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/gdc_client-v1.0.1-py2.6.egg/EGG-INFO/scripts/gdc-client", line 7, in <module>
    from gdc_client import download, upload, interactive
  File "/usr/lib/python2.6/site-packages/gdc_client-v1.0.1-py2.6.egg/gdc_client/upload/__init__.py", line 1, in <module>
    from . import parser
  File "/usr/lib/python2.6/site-packages/gdc_client-v1.0.1-py2.6.egg/gdc_client/upload/parser.py", line 11, in <module>
    from .client import GDCUploadClient
  File "/usr/lib/python2.6/site-packages/gdc_client-v1.0.1-py2.6.egg/gdc_client/upload/client.py", line 505
    keys.append({ele.tag.split('}')[-1]: ele.text for ele in element})
                                                    ^
SyntaxError: invalid syntax

**Comment by purplepeopleeater** [comment]
Github issues are not routinely monitored by the GDC team.  For questions to the GDC please contact the GDC Help Desk (support@nci-gdc.datacommons.io).    
--GDC Support Team
