### ISSUE TITLE
Libxslt.so.1

### ISSUE THREAD

**Issue by jiaren-zhang** [NCI-GDC/gdc-client#115]
Hi, i met this issue when running GDC-CLIENT:
Traceback (most recent call last):
  File "./gdc-client", line 7, in <module>
    from gdc_client import download, upload, interactive
  File "build/bdist.linux-x86_64/egg/gdc_client/upload/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/gdc_client/upload/parser.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/gdc_client/upload/client.py", line 6, in <module>
ImportError: libxslt.so.1: cannot open shared object file: No such file or directory

Would someone help me with this?

Thanks.

**Comment by svenmh** [comment]
There should be a package that holds libxslt.so, on CentOS it's called `libxslt`.  Try installing that.

**Comment by purplepeopleeater** [comment]
Github issues are not routinely monitored by the GDC team.  For questions to the GDC please contact the GDC Help Desk (support@nci-gdc.datacommons.io).    
--GDC Support Team
