### ISSUE TITLE
ImportError: /public/home/zzh/.pyenv/versions/2.7.13/lib/python2.7/site-packages/lxml-3.5.0b1-py2.7-linux-x86_64.egg/lxml/etree.so: undefined symbol: xmlBufContent

### ISSUE THREAD

**Issue by steven-zheng** [NCI-GDC/gdc-client#120]
Hi, i met this issue when running ./gdc-client:
Traceback (most recent call last):
  File "./gdc-client", line 7, in <module>
    from gdc_client import download, upload, interactive
  File "build/bdist.linux-x86_64/egg/gdc_client/upload/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/gdc_client/upload/parser.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/gdc_client/upload/client.py", line 6, in <module>
ImportError: /public/home/zzh/.pyenv/versions/2.7.13/lib/python2.7/site-packages/lxml-3.5.0b1-py2.7-linux-x86_64.egg/lxml/etree.so: undefined symbol: xmlBufContent
 
Would someone help me with this?
Thanks.

**Comment by purplepeopleeater** [comment]
Github issues are not routinely monitored by the GDC team.  For questions to the GDC please contact the GDC Help Desk (support@nci-gdc.datacommons.io).    
--GDC Support Team
